import type { Category, Site } from './typings/type'

// 常用网站（置顶）
export const pinnedSites: Site[] = [
  { name: '开源中国', url: 'https://www.oschina.net/' },
  { name: 'InfoQ', url: 'https://www.infoq.cn/' },
  { name: '今日热榜', url: 'https://tophub.today/' },
  { name: 'GitHub', url: 'https://github.com' },
  { name: 'Gitee', url: 'https://gitee.com/' },
  { name: 'dockerhub', url: 'https://hub.docker.com/' },
  { name: 'CSDN', url: 'https://www.csdn.net/' },
  { name: '豆瓣', url: 'https://douban.com/' },
  { name: '知乎', url: 'https://www.zhihu.com' },
  { name: '大疆', url: 'https://www.dji.com/cn' },
  { name: '小米', url: 'https://mi.com/' },
  { name: 'vivo', url: 'https://www.vivo.com.cn/' },
  { name: 'oppo', url: 'https://www.oppo.com/' },
  { name: '苹果', url: 'https://www.apple.com.cn/' },
  { name: '京东', url: 'https://www.jd.com/' },
  { name: '淘宝', url: 'https://www.taobao.com/' },
  { name: '虎扑', url: 'https://www.hupu.com/' },
  { name: '斗鱼', url: 'https://www.douyu.com/' },
  { name: '虎牙', url: 'https://www.huya.com/myfollow' },
  { name: '抖音', url: 'https://www.douyin.com/' },
  { name: 'B站', url: 'https://www.bilibili.com' },
  { name: '懂车帝', url: 'https://www.dongchedi.com/' },
  { name: '直播吧', url: 'https://zhibo8.cc/' },
  { name: '央视', url: 'https://www.cctv.com/' },
  { name: '广东TV', url: 'https://www.gdtv.cn/' },
  { name: '咪咕体育', url: 'https://www.miguvideo.com/' },
  { name: '微博', url: 'https://weibo.com' },
  { name: '思维导图', url: 'https://www.processon.com/' },
  { name: 'AI大全', url: 'https://www.msn.cn/zh-cn/gaming/ai' },
  { name: 'uni-app-x', url: 'https://doc.dcloud.net.cn/uni-app-x/' },
  { name: 'spring-boot', url: 'https://spring.io/projects/spring-boot' },
  { name: 'mybatis-flex', url: 'https://mybatis-flex.com/' },
  { name: 'mybatis-plus', url: 'https://baomidou.com/' },
  { name: 'sa-token', url: 'https://sa-token.cc/' },
  { name: 'Golang', url: 'https://golang.google.cn/dl/' },
  { name: 'Casbin', url: 'https://casbin.org/zh/docs/get-started' },
  { name: 'Gorm', url: 'https://gorm.io/zh_CN/docs/index.html' },
  { name: 'Xorm', url: 'https://xorm.io/zh/docs/' },
  { name: 'Vue', url: 'https://cn.vuejs.org/guide/introduction.html' },
  { name: 'Vite', url: 'https://cn.vite.dev/guide/' },
  { name: 'naive-ui', url: 'https://www.naiveui.com/zh-CN/os-theme' },
  { name: 'pro-naive-ui', url: 'https://naive-ui.pro-components.cn/zh-CN/os-theme' },
  { name: 'element-plus', url: 'https://element-plus.org/zh-CN/' },
  { name: 'Soybean', url: 'https://docs.soybeanjs.cn/zh/' },
  { name: 'pureadmin', url: 'https://pure-admin.cn/' },
  { name: 'liwenzhou', url: 'https://www.liwenzhou.com/' },
  { name: 'Youlai', url: 'https://www.youlai.tech/vue-docs/' },
  { name: 'RuoYi-Plus', url: 'https://plus-doc.dromara.org/' },
  { name: 'RuoYi', url: 'https://ruoyi.vip/' },
  { name: 'dromara', url: 'https://dromara.org/zh/' },
  { name: 'knife4j', url: 'https://doc.xiaominfo.com/' },
]

// 侧边栏网站分类
export const categories: Category[] = [
  {
    name: '排行',
    sites: [
      { name: '互联网技术', url: 'https://w3techs.com/' },
      { name: '数据库', url: 'https://db-engines.com/en/ranking' },
      { name: '编程语言', url: 'https://www.tiobe.com/tiobe-index/' },
      { name: 'linux发行版', url: 'https://distrowatch.com/' },
      { name: '电脑硬件排行', url: 'https://rank.kkj.cn/' },
    ],
  },
  {
    name: '设计资源',
    sites: [
      { name: 'Iconfont', url: 'https://www.iconfont.cn' },
      { name: 'Figma', url: 'https://figma.com' },
      { name: 'Dribbble', url: 'https://dribbble.com' },
      { name: 'Unsplash', url: 'https://unsplash.com' },
      { name: 'Color Hunt', url: 'https://colorhunt.co' },
    ],
  },
  {
    name: '学习平台',
    sites: [
      { name: '慕课网', url: 'https://www.imooc.com' },
      { name: '网易云课堂', url: 'https://study.163.com' },
      { name: '腾讯课堂', url: 'https://ke.qq.com' },
      { name: 'Coursera', url: 'https://www.coursera.org' },
      { name: 'edX', url: 'https://www.edx.org' },
      { name: '学堂在线', url: 'https://www.xuetangx.com' },
    ],
  },
  {
    name: '娱乐休闲',
    sites: [
      { name: '爱奇艺', url: 'https://www.iqiyi.com' },
      { name: '腾讯视频', url: 'https://v.qq.com' },
      { name: '优酷', url: 'https://www.youku.com' },
      { name: '网易云音乐', url: 'https://music.163.com' },
      { name: '喜马拉雅', url: 'https://www.ximalaya.com' },
    ],
  },
  {
    name: '新闻',
    sites: [
      { name: 'BBC', url: 'https://www.bbc.com/' },
      { name: '大公网香港', url: 'http://www.takungpao.com.hk/' },
      { name: '大公网中国', url: 'http://cn.takungpao.com/' },
      { name: 'BBC中文', url: 'https://www.bbc.com/zhongwen/trad' },
      { name: '凤凰网', url: 'https://www.ifeng.com/' },
      { name: '明报', url: 'https://www.mingpao.com/' },
      { name: '香港商报', url: 'https://www.hkcd.com.hk/' },
      { name: '香港01', url: 'https://www.hk01.com/' },
      { name: '台湾壹苹', url: 'https://tw.nextapple.com/' },
      { name: '香港无线新闻', url: 'https://news.tvb.com/tc' },
      { name: '台湾中时新闻', url: 'https://www.chinatimes.com/?chdtv' },
      { name: '台湾ettoday新闻', url: 'https://www.ettoday.net/' },
      { name: '台湾联合新闻', url: 'https://udn.com/news/index' },
      { name: '台湾中视', url: 'https://www.ctv.com.tw/News' },
      { name: '台湾TVBS', url: 'https://news.tvbs.com.tw/' },
      { name: '台湾中天新闻', url: 'https://ctinews.com/' },
      { name: '台湾民视新闻', url: 'https://www.ftvnews.com.tw/' },
      { name: '台湾年代新闻', url: 'https://www.eracom.com.tw/EraNews/' },
      { name: '台湾东森新闻', url: 'https://news.ebc.net.tw/' },
      { name: '台湾壹电视新闻', url: 'https://www.nexttv.com.tw/NextTV/News/' },
      { name: '台湾台视新闻', url: 'https://news.ttv.com.tw/' },
      { name: '台湾公视新闻', url: 'https://news.pts.org.tw/' },
      { name: '朝鲜劳动新闻', url: 'http://www.rodong.rep.kp/cn/' },
      { name: '朝鲜之声', url: 'http://www.vok.rep.kp/index.php/home/main/ch' },
      { name: '华尔街日报', url: 'https://cn.wsj.com/' },
      { name: '英为财情', url: 'https://cn.investing.com/' },
    ],
  },
  {
    name: '本地云',
    sites: [
      { name: 'excalidraw', url: 'http://draw.oby.ink' },
      { name: 'gitea', url: 'http://gitea.oby.ink' },
      { name: 'minio', url: 'http://minio.oby.ink' },
      { name: 'player', url: 'http://player.oby.ink' },
      { name: 'sql2go', url: 'http://sql2go.oby.ink' },
      { name: 'webhook', url: 'http://webhook.oby.ink' },
      { name: 'yml2go', url: 'http://yml2go.oby.ink' },
      { name: 'frps', url: 'http://frps.oby.ink' },
      { name: 'json2go', url: 'http://json2go.oby.ink' },
      { name: 'mirrors', url: 'http://mirrors.oby.ink' },
      { name: 'pwd', url: 'http://pwd.oby.ink' },
      { name: 'wx', url: 'http://wx.oby.ink' },
      { name: 'nav', url: 'http://nav.oby.ink' },
    ],
  },
]
